// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelClaude(arg1) {
  return window['go']['main']['App']['CancelClaude'](arg1);
}

export function CheckClaudeVersion() {
  return window['go']['main']['App']['CheckClaudeVersion']();
}

export function CleanupFinishedProcesses() {
  return window['go']['main']['App']['CleanupFinishedProcesses']();
}

export function CleanupOldCheckpoints(arg1) {
  return window['go']['main']['App']['CleanupOldCheckpoints'](arg1);
}

export function ClearCheckpointManager(arg1) {
  return window['go']['main']['App']['ClearCheckpointManager'](arg1);
}

export function ContinueClaude(arg1, arg2, arg3) {
  return window['go']['main']['App']['ContinueClaude'](arg1, arg2, arg3);
}

export function CreateAgent(arg1) {
  return window['go']['main']['App']['CreateAgent'](arg1);
}

export function CreateCheckpoint(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['CreateCheckpoint'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateProject(arg1) {
  return window['go']['main']['App']['CreateProject'](arg1);
}

export function DeleteAgent(arg1) {
  return window['go']['main']['App']['DeleteAgent'](arg1);
}

export function DeleteSlashCommand(arg1) {
  return window['go']['main']['App']['DeleteSlashCommand'](arg1);
}

export function ExecuteAgent(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteAgent'](arg1, arg2, arg3);
}

export function ExecuteClaude(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExecuteClaude'](arg1, arg2, arg3);
}

export function ExportAgent(arg1) {
  return window['go']['main']['App']['ExportAgent'](arg1);
}

export function ExportAgentToJSON(arg1) {
  return window['go']['main']['App']['ExportAgentToJSON'](arg1);
}

export function FindClaudeMdFiles(arg1) {
  return window['go']['main']['App']['FindClaudeMdFiles'](arg1);
}

export function ForkFromCheckpoint(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['ForkFromCheckpoint'](arg1, arg2, arg3, arg4, arg5);
}

export function GetAgent(arg1) {
  return window['go']['main']['App']['GetAgent'](arg1);
}

export function GetAgentRun(arg1) {
  return window['go']['main']['App']['GetAgentRun'](arg1);
}

export function GetAgentSessionOutput(arg1, arg2) {
  return window['go']['main']['App']['GetAgentSessionOutput'](arg1, arg2);
}

export function GetAgentSessionStatus(arg1, arg2) {
  return window['go']['main']['App']['GetAgentSessionStatus'](arg1, arg2);
}

export function GetCheckpointDiff(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['GetCheckpointDiff'](arg1, arg2, arg3, arg4);
}

export function GetCheckpointSettings(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetCheckpointSettings'](arg1, arg2, arg3);
}

export function GetClaudeBinaryPath() {
  return window['go']['main']['App']['GetClaudeBinaryPath']();
}

export function GetClaudeSessionOutput(arg1, arg2) {
  return window['go']['main']['App']['GetClaudeSessionOutput'](arg1, arg2);
}

export function GetClaudeSessionStatus(arg1, arg2) {
  return window['go']['main']['App']['GetClaudeSessionStatus'](arg1, arg2);
}

export function GetClaudeSettings() {
  return window['go']['main']['App']['GetClaudeSettings']();
}

export function GetHomeDirectory() {
  return window['go']['main']['App']['GetHomeDirectory']();
}

export function GetProjectSessions(arg1) {
  return window['go']['main']['App']['GetProjectSessions'](arg1);
}

export function GetProxySettings() {
  return window['go']['main']['App']['GetProxySettings']();
}

export function GetRecentlyModifiedFiles(arg1, arg2) {
  return window['go']['main']['App']['GetRecentlyModifiedFiles'](arg1, arg2);
}

export function GetSessionStats(arg1, arg2) {
  return window['go']['main']['App']['GetSessionStats'](arg1, arg2);
}

export function GetSessionTimeline(arg1, arg2, arg3) {
  return window['go']['main']['App']['GetSessionTimeline'](arg1, arg2, arg3);
}

export function GetSlashCommand(arg1) {
  return window['go']['main']['App']['GetSlashCommand'](arg1);
}

export function GetUsageByDateRange(arg1, arg2) {
  return window['go']['main']['App']['GetUsageByDateRange'](arg1, arg2);
}

export function GetUsageStats() {
  return window['go']['main']['App']['GetUsageStats']();
}

export function ImportAgent(arg1) {
  return window['go']['main']['App']['ImportAgent'](arg1);
}

export function ImportAgentFromJSON(arg1) {
  return window['go']['main']['App']['ImportAgentFromJSON'](arg1);
}

export function KillAgentSession(arg1) {
  return window['go']['main']['App']['KillAgentSession'](arg1);
}

export function ListAgentRuns(arg1) {
  return window['go']['main']['App']['ListAgentRuns'](arg1);
}

export function ListAgents() {
  return window['go']['main']['App']['ListAgents']();
}

export function ListCheckpoints(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListCheckpoints'](arg1, arg2, arg3);
}

export function ListClaudeInstallations() {
  return window['go']['main']['App']['ListClaudeInstallations']();
}

export function ListDirectoryContents(arg1) {
  return window['go']['main']['App']['ListDirectoryContents'](arg1);
}

export function ListProjects() {
  return window['go']['main']['App']['ListProjects']();
}

export function ListRunningClaudeSessions() {
  return window['go']['main']['App']['ListRunningClaudeSessions']();
}

export function ListSlashCommands() {
  return window['go']['main']['App']['ListSlashCommands']();
}

export function LoadSessionHistory(arg1, arg2) {
  return window['go']['main']['App']['LoadSessionHistory'](arg1, arg2);
}

export function MCPAddServer(arg1, arg2) {
  return window['go']['main']['App']['MCPAddServer'](arg1, arg2);
}

export function MCPAddServerFromJSON(arg1, arg2) {
  return window['go']['main']['App']['MCPAddServerFromJSON'](arg1, arg2);
}

export function MCPGetServer(arg1) {
  return window['go']['main']['App']['MCPGetServer'](arg1);
}

export function MCPGetServerStatus(arg1) {
  return window['go']['main']['App']['MCPGetServerStatus'](arg1);
}

export function MCPListServers() {
  return window['go']['main']['App']['MCPListServers']();
}

export function MCPReadProjectConfig(arg1) {
  return window['go']['main']['App']['MCPReadProjectConfig'](arg1);
}

export function MCPRemoveServer(arg1) {
  return window['go']['main']['App']['MCPRemoveServer'](arg1);
}

export function MCPResetProjectChoices(arg1) {
  return window['go']['main']['App']['MCPResetProjectChoices'](arg1);
}

export function MCPSaveProjectConfig(arg1) {
  return window['go']['main']['App']['MCPSaveProjectConfig'](arg1);
}

export function MCPTestConnection(arg1) {
  return window['go']['main']['App']['MCPTestConnection'](arg1);
}

export function OpenExternal(arg1) {
  return window['go']['main']['App']['OpenExternal'](arg1);
}

export function OpenFileDialog(arg1) {
  return window['go']['main']['App']['OpenFileDialog'](arg1);
}

export function OpenNewSession() {
  return window['go']['main']['App']['OpenNewSession']();
}

export function ReadClaudeMdFile(arg1) {
  return window['go']['main']['App']['ReadClaudeMdFile'](arg1);
}

export function RestoreCheckpoint(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['RestoreCheckpoint'](arg1, arg2, arg3, arg4);
}

export function ResumeClaude(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ResumeClaude'](arg1, arg2, arg3, arg4);
}

export function SaveClaudeMdFile(arg1, arg2) {
  return window['go']['main']['App']['SaveClaudeMdFile'](arg1, arg2);
}

export function SaveClaudeSettings(arg1) {
  return window['go']['main']['App']['SaveClaudeSettings'](arg1);
}

export function SaveFileDialog(arg1) {
  return window['go']['main']['App']['SaveFileDialog'](arg1);
}

export function SaveProxySettings(arg1) {
  return window['go']['main']['App']['SaveProxySettings'](arg1);
}

export function SaveSlashCommand(arg1) {
  return window['go']['main']['App']['SaveSlashCommand'](arg1);
}

export function SearchFiles(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchFiles'](arg1, arg2, arg3);
}

export function SetClaudeBinaryPath(arg1) {
  return window['go']['main']['App']['SetClaudeBinaryPath'](arg1);
}

export function StorageDeleteRow(arg1, arg2) {
  return window['go']['main']['App']['StorageDeleteRow'](arg1, arg2);
}

export function StorageExecuteSQL(arg1, arg2) {
  return window['go']['main']['App']['StorageExecuteSQL'](arg1, arg2);
}

export function StorageInsertRow(arg1, arg2) {
  return window['go']['main']['App']['StorageInsertRow'](arg1, arg2);
}

export function StorageListTables() {
  return window['go']['main']['App']['StorageListTables']();
}

export function StorageReadTable(arg1, arg2, arg3) {
  return window['go']['main']['App']['StorageReadTable'](arg1, arg2, arg3);
}

export function StorageResetDatabase() {
  return window['go']['main']['App']['StorageResetDatabase']();
}

export function StorageUpdateRow(arg1, arg2, arg3) {
  return window['go']['main']['App']['StorageUpdateRow'](arg1, arg2, arg3);
}

export function TrackCheckpointMessage(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TrackCheckpointMessage'](arg1, arg2, arg3, arg4);
}

export function TrackFileModification(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['TrackFileModification'](arg1, arg2, arg3, arg4);
}

export function UpdateAgent(arg1) {
  return window['go']['main']['App']['UpdateAgent'](arg1);
}

export function UpdateCheckpointSettings(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['UpdateCheckpointSettings'](arg1, arg2, arg3, arg4);
}
